CREATE TABLE COMPANY (
COMPANY_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
COMPANY_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE EMPLOYEE (
ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
EMPLOYEE_NAME VARCHAR(255) NOT NULL,
AGE BIGINT NOT NULL,
SALARY BIGINT NOT NULL,
GENDER VARCHAR(255) NOT NULL,
COMPANY_ID BIGINT,
FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID)
);