DELETE FROM EMPLOYEE;
DELETE FROM COMPANY;

INSERT INTO COMPANY(COMPANY_ID,COMPANY_NAME)
VALUES (1,'OOCL');
INSERT INTO COMPANY(COMPANY_ID,COMPANY_NAME)
VALUES (2,'COSCO');
INSERT INTO COMPANY(COMPANY_ID,COMPANY_NAME)
VALUES (3,'OOL');

INSERT INTO EMPLOYEE(ID,EMPLOYEE_NAME,AGE,SALARY,GENDER,COMPANY_ID)
VALUES (1,'Leo',16,5000,'Male',1);
INSERT INTO EMPLOYEE(ID,EMPLOYEE_NAME,AGE,SALARY,GENDER,COMPANY_ID)
VALUES (2,'Alfred',16,5000,'Male',2);
INSERT INTO EMPLOYEE(ID,EMPLOYEE_NAME,AGE,SALARY,GENDER,COMPANY_ID)
VALUES (3,'Prince',16,5000,'Male',3);